### PR TITLE
Update module.d.ts

### PR DESCRIPTION
**Pull request by lifeiscontent**

### CODE REVIEW

**Comment by theKashey** [comment]
Oh, my bad.

**Comment by lifeiscontent** [comment]
@theKashey if you want to fill in the blanks I left `any`'s in that'd be cool. I wasn't sure exactly what I should of put there.

**Comment by theKashey** [comment]
Sometimes it is very hard to fight `any`s. Here just some any could be replaced by object, and in one case by generic. And it will not change anything :(

**Comment by lifeiscontent** [comment]
@theKashey if I had more time, I'm 100% sure I could make all of them not return any. I just don't know the entire set of interfaces in the codebase.

**Comment by theKashey** [comment]
```tsx
  interface LoadableComponentState<P> {
    state: 'loading' | 'done' | 'error'
    AsyncComponent: Component<P>;  <----
  }

 interface ErrorComponentProps {
    retryAction: () => void,
    error: Error
 };

  type ComponentOptions<P> = {
    LoadingComponent?: Component<K>, // <---
    ErrorComponent?: Component<K | ErrorComponentProps>,
    exportPicker?: (a: any) => any,
    onError?: (a: Error/*does it exists*/) => void, <---
    render?: (component: Component<P>, state: LoadableComponentState<P>, props: K) => JSX.Element;
  }

  interface HOC {
    <P, K>(loader: () => Promise<DefaultComponent<P>>, options?: ComponentOptions<P, K>): Component<P>;
  }
```

Where P is the props of imported component, and K is props passed down to it. I am not even 50% sure that "K" is doable. But it shall be Object, not any.

Can you double check this interface?

**Comment by lifeiscontent** [comment]
Looks reasonable to me, I just realized instead of having a specific type called `Component` you should just use `React.ComponentType` which effectively does the same thing you're doing in the file.

**Pull request merged**
