### PR TITLE
Migrate to TypeScript and Refactor All The Things

### PR DESCRIPTION
**Pull request by theKashey**
- hook based, including `useImported(anything)`
- smaller
- with `boot` and `server` as separate entry points.

### CODE REVIEW

**Comment by theKashey** [comment]
https://www.npmjs.com/package/react-imported-component/v/6.0.0-beta.1

**Comment by wmertens** [comment]
I haven't read the whole changeset yet, but any chance of incorporating the preload tagging we discussed in https://github.com/theKashey/react-imported-component/issues/42#issuecomment-440291673?

**Comment by theKashey** [comment]
@wmertens - so yes and no.
- yes. I will have to introduce some helpers for webpack, and preloading might come as a part of it
- no. It's not _really_ required. New [boot scheduling](https://github.com/theKashey/react-imported-component/blob/type-friends/README.md#concurrent-loading) working almost as good as preloading.

**Comment by wmertens** [comment]
Well, if you can emit the required js in the html, then the browser preloader can fetch those files even before it finished parsing the html. So it will reduce latency even vs boot scheduling.

**Comment by theKashey** [comment]
Nowadays scripts could be downloaded much faster than executed. That's the trick - adding scripts to the HTML is not always making them "faster" to load.

**Pull request merged**
